import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.grid}>
      <Head>
        <title>Joseph Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid__greet}>
        <h1>Hi, my name is</h1>
        <h1 className={styles.grid__intro_name}>Fomonyutar Joseph</h1>
        <h1>I build Web and Mobile Applications</h1>
      </div>

      <div className={styles.grid__intro}>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde nam
          delectus explicabo quisquam minima nihil quod ab optio sequi corrupti.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, cum
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda,
          magnam!
        </p>
      </div>
      <div className={styles.grid__button}>
       <Button text="See More About Me"/>
      </div>

     
    </div>
  );
};

export default Home;
